### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by goncaloneves** [juanjoDiaz/serverless-plugin-warmup#101]
Hi,

I don't have time to keep up with these serverless projects for sometime now.

Since the project exists under Fidel, it makes more sense to have a main maintainer from the organisation.

cc: @andrelias @favio41 @juanjoDiaz 

Cheers

**Comment by juanjoDiaz** [comment]
I'd be happy to take the role if the Fidels guys are too busy (and am happy to keep the repo here or move it to my own GitHub).

This has been blocking https://github.com/FidelLimited/serverless-plugin-warmup/issues/84 and the releases for some time now.

Thanks, @goncaloneves, for the good work here! I hope you can still contribute occasionally :)

**Comment by goncaloneves** [comment]
@juanjoDiaz I appreciate your interest. :)
Thanks for caring for the project. Your help and activity have been precious and vital to this little plugin.

Fidel guys will come back to you soon.

Life is a bit rocky right now, when things are in shape it will certainly be a pleasure contributing again. 🙏

**Comment by favio41** [comment]
I will discuss this with Fidel's CTO, and comeback to you guys.

Thank you both for your help on this project, it is good to know that there
a people looking for this.

Cheers.

**Comment by juanjoDiaz** [comment]
Hi @andrelias,

So you want me to be the main contributor but keep it under the Fidel Organization, right?

What I need is admin access to this repo so I can setup Travis (#84)  and do other administrative stuff and admin access to the npm repo so I can do releases (currently creating most of the issues that we have).

I'm happy to have a chat about other stuff. You can find my email on my profile and we can continue from there. 🙂

**Comment by juanjoDiaz** [comment]
Any progress on this? 🙂

**Comment by marcfielding1** [comment]
Hey congrats @juanjoDiaz - i've been away hence me being sloppy about offering any contributions please let me know if you need me to look at anything :-)
