### ISSUE TITLE
My admin rights to the NPM repo have been removed

### ISSUE THREAD

**Issue by juanjoDiaz** [juanjoDiaz/serverless-plugin-warmup#218]
I've been maintaining this project since early 2019 and I need admin rights in order to do so.

Would the guys at FidelLimited (@goncaloneves, or whoever is there nowadays) prefer me to move the project to my own GitHub?

**Comment by juanjoDiaz** [comment]
Ping to @andrelias

**Comment by juanjoDiaz** [comment]
Pinging @diogogvhenriques as the las Fidel person with GitHub activity.

**Comment by diogogvhenriques** [comment]
Hi @juanjoDiaz Thank you so much for picking this, we just granted you admin access to the project

**Comment by juanjoDiaz** [comment]
Awesome, thanks!

Everything is back to normal!
As I've mentioned in the past. If you at Fidel would like to get rid of the repo ownership I'm happy to transfer it to my account and keep the mention to Fidel contributions in the readme. 🙂 

Closing this as it's solved.

**Comment by juanjoDiaz** [comment]
Pinging also @ccorneliu as the last committer in Fidel public repos

**Comment by diogogvhenriques** [comment]
Hi @juanjoDiaz 
Apologies for the slow response, will check with the team that can help you solve the problem.

**Comment by juanjoDiaz** [comment]
No worries.
As I mentioned, since I am the only maintainer of this package, the best option is for you to transfer the ownership in NPM as well.

That way you don't have to include me into your organization and manage my access rights, and this won't happen again. :)

**Comment by diogogvhenriques** [comment]
Hi @juanjoDiaz apologies for the delay on this.
I think the documentation that shared seems outdated or at least not accurate to the settings we have. With that said, you should have access to the package again, once you have it, if not we will look into it again.

**Comment by juanjoDiaz** [comment]
Thanks @diogogvhenriques !

I was able now to publish.
Still, I'd be more comfortable if we could transfer the repo ownership to avoid this issue in the future.

I reached out to NPM and they have send an email to developer@fidel.uk requesting for authorization to transfer the package to me. So all that's left is for you guys to answer to that email. 🙂

**Comment by juanjoDiaz** [comment]
Hi @diogogvhenriques,

Could you answer to that NPM email please?

**Comment by diogogvhenriques** [comment]
apologies for the delay @juanjoDiaz  since I'm not the owner of the email I could not reply directly.
I chased again the person with access, they should have replied by now
