### ISSUE TITLE
Can't configure warmup rate

### ISSUE THREAD

**Issue by RogerVFbr** [juanjoDiaz/serverless-plugin-warmup#236]
I've tried many configs, Amazon Eventbridge still states the warmup function is being called every 5 minutes:
<img width="187" alt="Screen Shot 2020-12-18 at 17 47 29" src="https://user-images.githubusercontent.com/29904392/102660007-1d09ac00-4159-11eb-9595-4eaa7917d0c9.png">
 
Aside from that the plugin works, but I need it to have a 4 minute rate. My YML:
<img width="279" alt="Screen Shot 2020-12-18 at 17 48 39" src="https://user-images.githubusercontent.com/29904392/102660102-44f90f80-4159-11eb-98e2-af8c893edfba.png">
<img width="206" alt="Screen Shot 2020-12-18 at 17 49 00" src="https://user-images.githubusercontent.com/29904392/102660147-517d6800-4159-11eb-8d0a-d64887638fdc.png">

Plugin version is 4.9 (as per package.json):
<img width="347" alt="Screen Shot 2020-12-18 at 17 54 43" src="https://user-images.githubusercontent.com/29904392/102660641-1d567700-415a-11eb-8a6c-b2709a9d9b5c.png">

Serverless framework version is:
<img width="427" alt="Screen Shot 2020-12-18 at 17 55 39" src="https://user-images.githubusercontent.com/29904392/102660706-3f4ff980-415a-11eb-912b-d79257e011f8.png">

If anyone else is facing this issue, my current workaround is overwriting the scheduling by adding the following resource on the resources section:
<img width="339" alt="Screen Shot 2020-12-18 at 18 34 23" src="https://user-images.githubusercontent.com/29904392/102663450-a91ed200-415f-11eb-8027-5faa26e5f3e4.png">
It has to have this exact name "WarmUpPluginEventsRuleSchedule1", and it will overwrite the one generated by the plugin.

 Any clues on this one? I went for the docs on NPM and Github, couldn't figure out the solution.

Thank you very much!

**Comment by juanjoDiaz** [comment]
Hi @RogerVFbr ,

Sorry I've totally missed this issue until now.

This is odd. The scheduling functionality is really battle-tested so I'm surprised that you are the only person facing this.
Have you tried to check the generated CloudFormation template to see what's the schedule for the warmer lambda?
Have you tried a different framework version?

**Comment by juanjoDiaz** [comment]
Closing since there is no response.
