### ISSUE TITLE
Container image support

### ISSUE THREAD

**Issue by lyzs90** [juanjoDiaz/serverless-plugin-warmup#239]
Was wondering whether it would be possible to support [container image](https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/) based lambda functions. The current spec requires a handler to be set and then the function gets packaged as a zip instead.

Thanks for your help!

**Comment by lyzs90** [comment]
Actually it works perfectly with container images! I misread the error when deploying the function

**Comment by streamline-uk** [comment]
@lyzs90 May I ask what your config looks like?

I am trying to deploy a container image and get this error with the warmup function:
`{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 's_warmUpPluginWarmer'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 's_warmUpPluginWarmer'",
    "Require stack:",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at _loadUserApp (/var/runtime/UserFunction.js:202:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:242:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
    "    at Module.load (internal/modules/cjs/loader.js:950:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",
    "    at internal/main/run_main_module.js:17:47"
  ]
}
`
