### ISSUE TITLE
Failure to install

### ISSUE THREAD

**Issue by elzayedv** [juanjoDiaz/serverless-plugin-warmup#248]
Error: Command failed: npm install --save-dev serverless-plugin-warmup@latest
  sh: 1: husky: not found
  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by rfoel** [comment]
This was introduced in the commit 88c3c27b0c23a76ba0110407777fd930377fe42c. Is there a reason to run `postinstall` here? This means all packages that install this plugin will run the `postinstall` from it.

**Comment by marcosmesser** [comment]
From [Husky docs](https://typicode.github.io/husky):

> if your package is not private and you're publishing it on a registry like npmjs.com, you need to disable postinstall script using pinst. Otherwise, postinstall will run when someone installs your package and result in an error.

**Comment by juanjoDiaz** [comment]
Damn! Totally missed that.

Although I don't like the idea of having an extra dependency just because of this....

**Comment by rfoel** [comment]
@juanjoDiaz why is a dev dependency a problem?

**Comment by juanjoDiaz** [comment]
Nothing inherently wrong with having a dev dependency.
But dependencies make the library heavier, increase attack surface, need to be maintain, etc.

In this case, I just don't think that it's justified to add a dependency.
And I don't think that modifying the package.json file on every publish is a great practice...

I've created a PR of what I consider a cleaner leaner approach. Feel free to comment on it. 🙂
