### ISSUE TITLE
Unresolved resource dependencies [WarmUpPluginDefaultLogGroup] in the Resources block of the template

### ISSUE THREAD

**Issue by JeffersonSchuler** [juanjoDiaz/serverless-plugin-warmup#252]
After upgrading from 5.1.2 to 5.2.0 using Serverless deployment to AWS Lambda, now seeing the following error on deployment.

> Error: The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [WarmUpPluginDefaultLogGroup] in the Resources block of the template

**Comment by juanjoDiaz** [comment]
Hi @JeffersonSchuler ,

I haven't been able to reproduce the issue. Can you provide an example repo that I can use for that?

**Comment by JeffersonSchuler** [comment]
If I get some time I will try to do that.  Here are my environmental settings as reported by Serverless.

Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.15.4
     Framework Version:         2.25.2
     Plugin Version:            4.4.3
     SDK Version:               2.3.2
     Components Version:        3.7.0

**Comment by awolad** [comment]
@juanjoDiaz Same issue here. Plugin version: `5.2.0`

**serverless.yml**

`provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: '*'

custom:
  warmup:
    default:
      enabled: true
      role: IamRoleLambdaExecution`

**Github CD**

![image](https://user-images.githubusercontent.com/9510958/108706439-d3628680-7538-11eb-85f1-a52dac698c6a.png)

**Comment by prakashn27** [comment]
Same error with version @5.2.0

**Comment by RomanDubovskyi** [comment]
Same error with version @5.2.0

**Comment by JeffersonSchuler** [comment]
The issue looks like it is resolved now with the 5.2.1. release.  Thank you!

**Comment by GVMafeedme** [comment]
The error has reapeared for me when updating to Serverless v3. 

**Environment**

- Framework core: 3.1.1
- Plugin: 6.0.0
- SDK: 4.3.1
- Running on Serverless CI/CD
- Deploying on AWS
- serverless-warmup-plugin: 7.0.1

**Build Log**
`
Warning: Invalid configuration encountered

  at 'functions.offerUploadBulkFile': unrecognized property 'iamRoleStatementsName'

  at 'functions.offerUploadBulkFile': unrecognized property 'iamRoleStatements'

  at 'functions.filesInitiateUpload': unrecognized property 'iamRoleStatementsName'

  at 'functions.filesInitiateUpload': unrecognized property 'iamRoleStatements'

Learn more about configuration validation here: http://slss.io/configuration-validation

Warning: WarmUp: Skipping warmer "default" creation. No functions to warm up.

× Stack offers-api-service-feat-gvm-600 failed to deploy (139s)

Environment: linux, node 14.15.5, framework 3.1.1 (local), plugin 6.0.0, SDK 4.3.1

Docs:        docs.serverless.com

Support:     forum.serverless.com

Bugs:        github.com/serverless/serverless/issues

Error:

The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [WarmUpPluginDefaultLogGroup] in the Resources block of the template
`

**Comment by juanjoDiaz** [comment]
Hi @GVMafeedme ,
Can you provide an example repo to replicate?

This is related to the lifecycle events hooks.
It's proving pretty hard to have hooks that work for all possible use cases and combinations of plugins and serverless pro functionality....

**Comment by GVMafeedme** [comment]
> Hi @GVMafeedme , Can you provide an example repo to replicate?
> 
> This is related to the lifecycle events hooks. It's proving pretty hard to have hooks that work for all possible use cases and combinations of plugins and serverless pro functionality....

It works correctly on version 7.0.2 thank you!
