### ISSUE TITLE
AWS Lambda Handler Path Issues Deploy from Windows

### ISSUE THREAD

**Issue by sandyboyz** [juanjoDiaz/serverless-plugin-warmup#255]
Hello,

I am using serverless-plugin-warmup and did the deployment from serverless-cli with windows as my operating system. However when I deploy to AWS Lambda. I realize that my lambda did not work and when I check node handler in aws-console it's become like this:

`.warmup\default\index.warmUp`  and of course the lambda failed to invoke with error `runtime.ImportModuleError`.

So I changed the `backslash `to `slash` and the lambda invoke successfully. 
So I think there is issues when I deploy from Windows because windows path style. Maybe can considering to force path to` '/' `because AWS Lambda only supported this path style.

**Comment by snarf-snarf-snarf** [comment]
I have the exact same problem, the warmup plugin deployed fine, I even downloaded the zip code from AWS and executed it locally and it worked. However, AWS can't invoke it due to the following error:

`"errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '/var/task'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '/var/task'",
        "Require stack:",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1063:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)",
        "    at Module.load (internal/modules/cjs/loader.js:928:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:769:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]`

Thanks to the post above I manually changed the handler for the lambda to use forward slashes and now it works fine.

**Comment by snarf-snarf-snarf** [comment]
Line 15 config.js is the problem path.join(folderName, 'index.warmUp'). This produces backslashes for me on Windows.

**Comment by snarf-snarf-snarf** [comment]
The solution is to require path.posix in config.js instead which uses forward slash on all Operating Systems I believe.

**Comment by juanjoDiaz** [comment]
Fixed in 5.2.2
