### ISSUE TITLE
index.js is empty when running Node 15.8.0

### ISSUE THREAD

**Issue by stuartleylandcole** [juanjoDiaz/serverless-plugin-warmup#256]
Firstly thank you for such a fantastic plugin, we have been using it for a long time on our project to great effect!

I have encountered an issue with version 5.0.0 wherein the index.js file that executes the warmup is blank when running Node 15.8.0. This causes an AWS error because it results in a zip file containing a file that is empty:

```
  Serverless Error ---------------------------------------
 
  An error occurred: WarmUpPluginDefaultLambdaFunction - Uploaded file must be a non-empty zip (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: xxxxx; Proxy: null).
```

I switched to version 15.2.1 and the file was correctly generated. There was nothing special about this version, it was the version a colleague had installed that could not replicate the above problem.

On a separate project we are using version 4.9.0 of the plugin and this works as expected with Node 15.8.0.

Hope this is useful but happy to provide anything else to help resolve the issue.

Thanks again for a great plugin.

**Comment by juanjoDiaz** [comment]
Any more info on this?

It sounds like something totally unrelated to this library.
Like a bug in the fs module, maybe related to the recursive option...
I reviewed Node's changelog but couldn't find anything that seems related...

**Comment by juanjoDiaz** [comment]
Closing since the issue seems to be related with Node and not with this plugin.

Feel free to reopen if you think that's needed.
