### ISSUE TITLE
Docs improvement: custom.warmup config is required

### ISSUE THREAD

**Issue by tonythree** [juanjoDiaz/serverless-plugin-warmup#257]
Hi there,
Thanks a lot for such a wonderful plugin. It has been very useful.
I followed your documentation on this README and in serverless webpage.
By doing so, I was having the following error:
```
TypeError: Cannot convert undefined or null to object
      at Function.entries (<anonymous>)
      at getConfigsByWarmer (...)
```
I solved by adding 
```
custom:
  warmup:
    default:
      enabled: true # Whether to warm up functions by default or not
```

But this, in my opinion, is not clear in the docs. There should be a paragraph saying that putting the "custom" part is necessary in order to work.
Can you reproduce the error or is it just happening on my machine?
Thanks again and hopefully this helps someone else :)

**Comment by juanjoDiaz** [comment]
Hi @tonythree ,

The first sentence of the configuration section says:

> The warmup plugin supports creating one or more warmer functions. Warmers are defined under custom.warmup in the serverless.yaml file:

If you have any suggestion to make this clearer, it's very welcome 🙂

**Comment by tonythree** [comment]
Thanks for your response.
I saw this, maybe changing "supports" by "requires"; or adding a line specifying that at least you require to define 1 warmer in order to make it work would make the documentation, in my opinion, easier to understand :)
I have worked with other plugins like `serverless-offline`, `serverless-python-requirements`etc. and this plugins does not require custom attributes (you can add some, but they are not needed in order to make the plugin work). Probably, this is why I supposed that a default warmer will be created automatically when installing the plugin.

Another possible solution would be, if nothing is found in custom.warmup, you can create a warmup with a default name and enabled by default. This is probably a bad practice in your specific case, so I would go with adding some clarification in the docs, and/or the simplest example like:
```
custom:
  warmup:
    myWarmer:
      enabled: true # Whether to warm up functions by default or not
```

Thanks for your response @juanjoDiaz, and for the wonderful plugin (it has been working flawlessly since last week).
