### ISSUE TITLE
zip error: Nothing to do! (../warmUpPluginOfficeHoursWarmer.zip)

### ISSUE THREAD

**Issue by chuckthepiranha** [juanjoDiaz/serverless-plugin-warmup#259]
I keep getting this error when I try deploying. I am not sure what I am missing. I have the latest versions of serverless and serverless-plugin-warmup and I have the following in my custom section of my serverless file: 

```
warmup: {
            officeHoursWarmer: {
                enabled: ["prod"],
                events: [{ schedule: "cron(0/5 0-5 ? * MON-SAT *)" }, { schedule: "cron(0/5 12-23 ? * MON-SAT *)" }],
                concurrency: 1
            }
        }
```
I have the following for the lambdas that I don't want warmed up:

```
warmup: {
        officeHoursWarmer: {
            enabled: false
        }
    }
```

This is the command that is failing in serverless-plugin-warmup: `zip --quiet --recurse-paths ../warmUpPluginOfficeHoursWarmer.zip`

Why is it not including a directory name for zipping? Thank you.

**Comment by chuckthepiranha** [comment]
I also get this warning when deploying: ``` Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - ServerlessPlugin for "out"
             - ServerlessOffline for "apiKey", "corsAllowHeaders", "corsAllowOrigin", "corsDisallowCredentials", "corsExposedHeaders", "disableCookieValidation", "enforceSecureCookies", "hideStackTraces", "host", "httpPort", "httpsProtocol", "lambdaPort", "noPrependStageInUrl", "noAuth", "ignoreJWTSignature", "noTimeout", "prefix", "printOutput", "resourceRoutes", "useChildProcesses", "useWorkerThreads", "websocketPort", "webSocketHardTimeout", "webSocketIdleTimeout", "useDocker", "layersDir", "dockerReadOnly", "functionCleanupIdleTimeSeconds", "allowCache", "dockerHost", "dockerHostServicePath", "dockerNetwork"
             - WarmUp for "warmers"
            Please report this issue in plugin issue tracker.```

Is there a specific version of serverless I need to use? I am using the latest one.

**Comment by juanjoDiaz** [comment]
Hi @chuckthepiranha ,

That warning is just a warning and doesn't break anything. In any case, it will be dealt with in the next release.

Everything looks correct in your config.
I don't fully understand the issue.
Are you calling `zip`? Or is the serverless framework failing when trying to zip?
Can you provide a more complete config and error so I can try to reproduce the issue?

**Comment by juanjoDiaz** [comment]
Closing since there is no response.
Feel free to reopen if there is anything else to do here.
