### ISSUE TITLE
function stays cold

### ISSUE THREAD

**Issue by gisraeliyotpo** [juanjoDiaz/serverless-plugin-warmup#262]
Hi i've added the plugin successfully and im seeing that it is invoking my function every 2 minutes

but when im calling the function im still getting cold start and it takes about a second to return

the function is very simple just return "Go Serverless" nothing more
i've tried to increase warmup concurrency to 2 didn't help

anyone else has this problem?

**Comment by juanjoDiaz** [comment]
Hi @gisraeliyotpo,

Can you see in the logs of the lambdas whether the warmer is calling the lambda every 2 minutes as expected?

**Comment by gisraeliyotpo** [comment]
Hi Thanks for the fast response!
yes we've checked the logs and see that it is being called every 2 minutes,
and looking inside cloudwatch logs you can see that the source is lambda warmup function

**Comment by iPherian** [comment]
@gisraeliyotpo If you look in the log stream and it's the second or more execution, then it's warmed up. If it's still slow then I don't know, it's just an AWS performance thing. You might be able to find info elsewhere.

**Comment by juanjoDiaz** [comment]
Closing since the issue went stale and @iPherian already provide a possible explanation (thanks mate!)

Feel free to reopen if there are still things pending.
