### ISSUE TITLE
Duplicated logs

### ISSUE THREAD

**Issue by GarrisonD** [juanjoDiaz/serverless-plugin-warmup#267]
I noticed that I have duplicated logs from `warmup` plugin and my first thought was that I did something wrong... But I found in other GitHub issues for this project the same output thus it's not related to config. It's interesting for me why it works this way and where the problem is?

```
> sls deploy

Serverless: WarmUp: Skipping warmer "default" creation. No functions to warm up.
Serverless: WarmUp: Skipping warmer "default" creation. No functions to warm up.
Serverless: Packaging service...
Serverless: Excluding development dependencies...
````

**Comment by juanjoDiaz** [comment]
Hi @GarrisonD ,

Sorry, this issue went totally unnoticed for me.
Can you share an example project to replicate this?

**Comment by juanjoDiaz** [comment]
Closing since there is no response.
