### ISSUE TITLE
example using an SQS lambda

### ISSUE THREAD

**Issue by oreporan** [juanjoDiaz/serverless-plugin-warmup#272]
Hello
I'm using your plugin successfully for http lambdas, 
However your plugin doesn't mention that it handles only `http` events, though all the example show `http` only.

What about this use case:

```yml
    events:
      - sqs: ...
```

Do I need to add a separate `http` event for the warmup to work? or will it work with sqs just as well?

**Comment by juanjoDiaz** [comment]
Hi @oreporan,

`http` events are synchronous. If the lambda is cold and take times to load, the user experience suffer. This plugin keep the lambdas warm to improve UX but has a small cost.
`sqs` and other asynchronous events don't have that problem. As they are asynchronous, it doesn't matter if the lambda is warm or not and it doesn't makes sense to pay the extra cost.

**Comment by juanjoDiaz** [comment]
Closing since the original question has been answered and there is no answer.
