### ISSUE TITLE
Would this work for a containerized function deployed with ECR? 

### ISSUE THREAD

**Issue by wtfzambo** [juanjoDiaz/serverless-plugin-warmup#273]
As title says:

I have a function that I needed to deploy using ECR due to the fact that it uses some heavy ML libraries that couldn't possibly fit within the lambda limits.

A cold start takes quite a while, and I was wondering if this plugin would work for this specific case, since I haven't seen any specifics as for what regards functions deployed with ECR.

Thanks in advance for any help!

**Comment by juanjoDiaz** [comment]
Hi @wtfzambo sorry for the delay. It seem that my previous answer never sent.

This plugin only works for lambda functions deployed using the serverless framework.
Whether the image comes from ECR or not should be totally irrelevant...

**Comment by wtfzambo** [comment]
@juanjoDiaz hey, don't worry, thanks for the reply!

I am indeed using Serverless Framework, with ECR as the source of my code:
```
functions:
  myFunc:
    image:
      name: latest
```
The reason I'm asking this is due to the fact that I saw a post on reddit which said that OP couldn't manage to make this work while having his function hosted on ECR. It sounded weird to me, which is why I asked. At this point I have the suspicion that that guy messed something up in the configuration.

I'll do some test and let you know!

**Comment by juanjoDiaz** [comment]
Closing since there seems to be no issue.
Feel free to reopen if you feel that there is anything left to tackle.

**Comment by wtfzambo** [comment]
@juanjoDiaz yo, sorry for the late update, anyway I just wanted to inform you that the plugin works flawlessly even with lambdas deployed using ECR. That guy on reddit must have messed something up!
