### ISSUE TITLE
 An error occurred: WarmUpPluginDefaultLogGroup - /aws/lambda/Lambda_name-dev already exists in stack

### ISSUE THREAD

**Issue by sumancholleti** [juanjoDiaz/serverless-plugin-warmup#277]
After Upgrading the version warmup plugin from 3.x to 5.2.1 we are getting the error below

 An error occurred: WarmUpPluginDefaultLogGroup - /aws/lambda/LambdaName-dev already exists in stack

With previous version it used to override it, please let me know if any one can help here
custom:  
  warmup:
    default:
      role: arn:aws:iam::ACCOUNT_ID:role/LambdaRole
      name: LambdaName-dev
      enabled: true
      memorySize: 256
      concurrency: 3
      vpc: false
      prewarm: true
      payload:
        source: warmup-trigger

**Comment by juanjoDiaz** [comment]
Hi @sumancholleti,

Were you able to fix this?

**Comment by LuiSanz** [comment]
I am facing this same issue. serverless is trying to create the role, which already exists.

**Comment by juanjoDiaz** [comment]
Any idea of why is the role already there?

I've tried deploying, deleting and deploying again without a problem.
The role is correctly created, destroyed and recreated again.

And if you deploy the same service to the same region and the same stage more than once it should simply update the stack for that deployment.

**Comment by juanjoDiaz** [comment]
Closing since there is no response and the issue can't be reproduce.
Feel free to reopen 🙂

**Comment by danmana** [comment]
We had a similar issue when upgrading an older lambda from serverless 2 to 3 (warmup 4.9 -> 8.2).
![image](https://github.com/juanjoDiaz/serverless-plugin-warmup/assets/498419/383be491-3149-4b3a-8c82-b910ec76fa94)


Not sure if it's related to the fact that we used to have one inline configuration for a warmup function, and now it's nested:
```yml
custom:
  warmup:
    default: # this level did not exist before
      enabled: true
```

The way we solved this was to:
1. temporarily disable the warmup plugin
```yml
plugins:
  # - serverless-plugin-warmup
```
2. deploy the stack (which will remove the old warmup resources)
3. re-enable the warmup plugin
4. deploy again (will re-create the warmup resources)
