### ISSUE TITLE
Support setting reserved concurrency for warmup lambdas

### ISSUE THREAD

**Issue by cschroed-usgs** [juanjoDiaz/serverless-plugin-warmup#283]
User story:
As a developer whose organization requires that all lambdas define a reserved concurrency amount, I want to set a reserved concurrency amount on the lambdas managed by the WarmUp plugin, so that I can keep my lambdas warm, while following my organization's rules.

**Comment by juanjoDiaz** [comment]
Duplicates #201 

If you think that it does not duplicate it, feel free to reopen with more details 🙂
