### ISSUE TITLE
Serverless Framework v3: new design & how to integrate

### ISSUE THREAD

**Issue by mnapoli** [juanjoDiaz/serverless-plugin-warmup#289]
Hi 👋 , Serverless Framework core team here!

We're working on the v3 beta version right now. The v3 will include a redesigned CLI output:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/720328/139266855-7c0c15e1-9201-48b6-92f0-db6af2da4d11.png">

You can try the v3 beta with: `npm i serverless@pre-3`

To help plugins integrate with that new design (and build a great user experience), we've added new APIs for plugins:

- [Video introduction (Youtube)](https://www.youtube.com/watch?v=K3IhZ9fImk4)
- [Documentation of the new API](https://www.serverless.com/framework/docs/guides/plugins/cli-output)

Any feedback is appreciated! If you want to update your plugin to use these new APIs, feel free to ping me if you have any questions!

If you don't have time to update the plugin, let me know, we can send a pull request!

**Comment by juanjoDiaz** [comment]
I have the changes implemented but I won't release them until v3 is out.

**Comment by mnapoli** [comment]
@juanjoDiaz got it, thank you for the update.

**Comment by batovpasha** [comment]
Hello everyone!
@juanjoDiaz Do you have changes for the JSON schema of the plugin to adhere to the strict mode that was added in the AJV v7, as SLS v3 updated it from the v6 to v8?
If not, I will be glad to make a PR.

**Comment by juanjoDiaz** [comment]
PRs are always welcome as long as they are clean, tested and maintain current test coverage.
The v3 branch is https://github.com/juanjoDiaz/serverless-plugin-warmup/tree/serverless_v3

**Comment by batovpasha** [comment]
Thank you for the reply! I am going to make a PR in a couple of nearest days.

**Comment by pgrzesik** [comment]
Hey @batovpasha - are you planning to address it in the coming days? If not, I'm happy to pick it up as we're aiming for a v3 release of Framework very soon

**Comment by batovpasha** [comment]
@pgrzesik Hello! Yes, I will make a PR for today/tomorrow.

**Comment by pgrzesik** [comment]
Awesome, thank you @batovpasha
