### ISSUE TITLE
New release for serverless v3 compatibility

### ISSUE THREAD

**Issue by dylan-hoefsloot** [juanjoDiaz/serverless-plugin-warmup#301]
The latest version of this package raises the following error when trying to use with serverless v3

```
Error: strict mode: missing type "object" for keyword "patternProperties" at "#/properties/custom/properties/warmup" (strictTypes)
```

I can see the fix has already been merged so adding the github repo as a dependency in `package.json` works in the mean time but an new package version would be ideal
```
"serverless-plugin-warmup": "https://github.com/juanjoDiaz/serverless-plugin-warmup",
```

**Comment by juanjoDiaz** [comment]
Solved by #297.
I will be releasing a new version today.
