### ISSUE TITLE
TypeError: Cannot destructure property 'log' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by stbth01** [juanjoDiaz/serverless-plugin-warmup#303]
Thanks for the plugin really appreciate it! 

We have been using the plugin without issue for several months now but tried upgrading to 7.0.0 this morning and got the error message below. I'm sorry if this not an issue but rather an implementation issue but I could not find obvious issue looking through the docs.

![image](https://user-images.githubusercontent.com/12235803/152008722-357fb698-3bac-4819-9a26-3b8eb99cee23.png)

We are not really doing much configuration:
![image](https://user-images.githubusercontent.com/12235803/152008807-f76a5284-b885-4883-8331-a551a81e9c34.png)

If we roll back to 6.2.0 the issue goes away.

Thank you so much for your help!

**Comment by stbth01** [comment]
A team member pointed out that we need to upgrade serverless to 3. We will try that but close this for now.

**Comment by juanjoDiaz** [comment]
Indeed.

To stay in Serverless prior to 3 you need to stay in version 0.X of this plugin. 🙂

**Comment by juanjoDiaz** [comment]
You are quite behind...

Reading at the release notes, it seems that I added Serverless v3 in 7.0.0.
So, you should be able to work with [6.2.0](https://github.com/juanjoDiaz/serverless-plugin-warmup/releases/tag/6.2.0)
If you are using a very old version of Serverless, you might need to go to an older version. Just check the [release notes](https://github.com/juanjoDiaz/serverless-plugin-warmup/releases?page=2).
