### ISSUE TITLE
Permissions when using alias

### ISSUE THREAD

**Issue by MartinRisk** [juanjoDiaz/serverless-plugin-warmup#304]
When using an alias the permission for the InvokeFunction should get an addition :* after the function name
Starting 

From AWS:
Currently, you can restrict the scope of a user's permissions to the Lambda function APIs by using an unqualified ARN in the Resource element of your IAM or VPC endpoint policy. Previously, when used in this way, Lambda interpreted such permissions in one of two ways depending on the API usage. Either by granting permission to requests to the function only, or granting permissions to requests to the function and all of its sub-resources. For example, when using IAM or VPC endpoint policy with resource element as unqualified ARN, arn:aws:lambda:aws-region:acct-id:function:helloworld, API Request(s) with qualified ARN as arn:aws:lambda:aws-region:acct-id:function:helloworld:42 is denied and the request using arn:aws:lambda:aws-region:acct-id:function:helloworld, Qualifier=42 is allowed. We received customer feedback that this dual interpretation was not always intuitive. To address this feedback and increase the consistency of the Lambda function APIs authorization, starting January 24, 2022, Lambda requires IAM or VPC endpoint policies to specify the fully qualified ARN in the Resource element when authorizing API calls that use an unqualified ARN with a qualifier parameter.

This change will begin on April 30, 2022, to give you ample time to update your IAM policies or permissions attached to the users and roles that call Lambda APIs before that.

**Comment by juanjoDiaz** [comment]
Thanks @MartinRisk !
Do you have a link to that statement?
I can't find the oficial source about this.

**Comment by MartinRisk** [comment]
Hi,

I received an Email about this change from AWS.
Found someone else with the same mail: https://forum.serverless.com/t/lambda-security-notification-from-aws-involving-iam-policies-need-help-determining-action-for-serverless-framework/16660 

Official doc: https://docs.aws.amazon.com/lambda/latest/dg/lambda-api-permissions-ref.html
Look in the Function resource names part.

"Whether you are allowing or denying an action on your function, you must use the correct function ARN types in your policy statement to achieve the results that you expect. For example, if your policy references the unqualified ARN, Lambda accepts requests that reference the unqualified ARN but denies requests that reference a qualified ARN."

"If your policy references any ARN using *, Lambda accepts any qualified or unqualified ARN."

**Comment by MartinRisk** [comment]
If you always add a * directly after the FunctionName (without a : ) it should be ok for qualified and unqualified calls

**Comment by juanjoDiaz** [comment]
Solved in v710
