### ISSUE TITLE
Error: warmup-plugin-default already exists in stack 

### ISSUE THREAD

**Issue by thomas-hallinan** [juanjoDiaz/serverless-plugin-warmup#305]
After upgrading to serverless-plugin-warmup 7.0.0 and serverless 3.1.1.  We get the following error.
Error:
CREATE_FAILED: WarmUpPluginDefaultLambdaVersionPa4zUdUsqDi4Lj3Yx9gTWlkZnz68iLzZZOLHeVZyaU (AWS::Lambda::Version)
function:blah-dev-warmup-plugin-default:25 already exists in stack 

We are seeing this in the logs:
Uploading service warmUpPluginDefault.zip file to S3 (1.18 kB)
Creating new change set
Waiting for new change set to be created
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying

When hardcoding to serverless-plugin-warmup version 6.2.0 and serverless version we don't have the error.

**Comment by juanjoDiaz** [comment]
This seems something related to Serverless and CloudFormation and not specifically to this plugin.

I'd suggest that you:
* Remove the WarmUp plugin (you can simply comment it out in `serverless.yaml`) and do a deployment
* Update to Serverless 3 and do a deployment
* Add the latest WarmUp plugin and do a deployment

Then you can see where the error is.

**Comment by thomas-hallinan** [comment]
Thanks.   You are correct, it's not the warmup plugin.  Thanks for the help.
