### ISSUE TITLE
Alternative event bus

### ISSUE THREAD

**Issue by brandon-constratum** [juanjoDiaz/serverless-plugin-warmup#326]
I've run out of Event Rules for deploying new warmups via the plugin, is it possible to choose another Event Bus for the rules?

I've applied for AWS quota limit increase from 300 rules but they have yet to approve it.

Edit:
I have also tried using the serverless eventBridge type but i get an error when adding the eventBus field
`Serverless:   at 'custom.warmup.default.events[0]': unrecognized property 'eventBus'`

**Comment by brandon-constratum** [comment]
Thanks for the reply,

Yeah 300 is a lot of warmers, we currently are using serverless as each "app" is an api so we have about 80 of those but then they are deployed across 3-4 stages all with warmers, so it adds up quickly, we are considering dropping warmers for our development stage which will help.

as far as i can tell an event bus almost acts like a folder for events which can be customised.

i think scheduled events and event bridge events are the same thing but you can just specify which bus they go on as they go on "default" without it.

**Comment by juanjoDiaz** [comment]
Hi @brandon-constratum ,

I've created a branch adding experimental support for eventBridge.
Unfortunately, I don't have time to test it.

You could install it using `npm install https://github.com/juanjoDiaz/serverless-plugin-warmup.git#add_event_bridge_support` and test it out.

If you do, please let me know how it goes 🙂

**Comment by juanjoDiaz** [comment]
Hi @brandon-constratum ,

I assume that you never tried the branch?
Did you find a workaround to your issue?

**Comment by brandon-constratum** [comment]
@juanjoDiaz hey!
Sorry, I didn't get around to it, it was a very busy time for me and I think by the time you were able to get to it (which I appreciate very much) AWS had increased our quota limit so we were able to continue as is and since then we have culled a lot of our exisiting versions and dev/testing stages that we no longer needed so we have ample event rules now.
