### ISSUE TITLE
Not working with Serverless Webpack

### ISSUE THREAD

**Issue by alienself** [juanjoDiaz/serverless-plugin-warmup#329]
Hi, 

Great plugin, I would love to use it in my project however I am having an issue when using `serverless-webpack` (https://github.com/serverless-heaven/serverless-webpack). 
I am using typescript and therefore needs serverless webpack to package my project.

The warmup plugin basically create a massive zip file containing the whole project (include the typescript files and the webpack packaged zip).

Any example on how to configure both packages to work together?
 
Thanks!

**Comment by juanjoDiaz** [comment]
Hi @alienself ,

Simply declare the warmup plugin after the webpack plugin and it should work.
If you have problems, please share your yaml file or some project to reproduce so I can take a look and try to help 🙂

**Comment by alienself** [comment]
Thanks for the quick reply! I was able to make it work by declaring the warmup plugin before the webpack plugin which solved the issue.
