### ISSUE TITLE
Websocket warmup

### ISSUE THREAD

**Issue by Travellerme** [juanjoDiaz/serverless-plugin-warmup#335]
Hello
I'm integrating websockets into our application based on the official article https://www.serverless.com/framework/docs/providers/aws/events/websocket/
And I have a question about how the warmup plugin works with WebSocket lambdas.
Unfortunately I did not find any info yet

- Do we need to warmup websocket lambdas to speed up the first connection ? 
- If we do, then how to warmup the websocket lambda that is placed behind the auth lambda?
Thank you

**Comment by juanjoDiaz** [comment]
Hi @Travellerme ,

Tob e honest, I've never considered websockets in the plugin.

The plugin just use the [AWS SDK invoke](https://docs.aws.amazon.com/en_en/lambda/latest/dg/API_Invoke.html) method to invoke the lambda. So, as long as your handler handles the warmup event as described in the docs it should work just fine.

**Comment by juanjoDiaz** [comment]
Hi @Travellerme ,

Did you progress on this?
