### ISSUE TITLE
Is the pricing still accurate in Readme?

### ISSUE THREAD

**Issue by its-me-ilia** [juanjoDiaz/serverless-plugin-warmup#340]
Hey, in readme.md, cost is broken down as such

8640 invocations per month per function with 10ms duration and 124mb allocated memory. Multiplied by 10 this adds up to ~ 14$.
I think this is outdated no? screenshot includes 8640 * 10 iterations, for 10 functions in current example. for single function (8640 invocations) cost is less than a cent.

<img width="813" alt="image" src="https://github.com/juanjoDiaz/serverless-plugin-warmup/assets/54749663/b1af7de8-69e2-4186-b368-ffd63d3bf840">

**Comment by juanjoDiaz** [comment]
Fixed
