### ISSUE TITLE
Deployment failed on Windows when using warmup plugin

### ISSUE THREAD

**Issue by yuyitan** [juanjoDiaz/serverless-plugin-warmup#341]
After adding serverless-plugin-warmup to the plugins section and adding the warmup config to my .yml file, I was unable to deploy using serverless. While the error is regarding usage of 'include/exclude' for patterns, it seems unrelated as this error occurs even when I remove the include/exclude.

This error does not occur on Mac but only on Windows machine. This error also goes away once I remove serverless-plugin-warmup from my .yml file and uninstall the plugin.

The version of serverless-plugin-warmup is stated "^8.2.1" in my package.json.

```
WarmUp: Creating warmer "default" to warm up 8 functions

× Stack <STACK_NAME> failed to deploy (24s)
Environment: win32, node 16.13.0, framework 3.27.0 (local) 3.30.1v (global), plugin 6.2.3, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
No file matches include / exclude patterns
```

**Comment by juanjoDiaz** [comment]
Hi,

@yuyitan, This kind of issue is typically caused by using another plugin like webpack, rollup, etc.
Can you share your `serverless.yaml`?

**Comment by juanjoDiaz** [comment]
Closing since there was no response.
Feel free to reopen if you have any more details.
