### ISSUE TITLE
getting issue when we update nodejs 18.x

### ISSUE THREAD

**Issue by juztinlazaro** [juanjoDiaz/serverless-plugin-warmup#342]
`ServerlessError: An error occurred: WarmUpPluginLambdaFunction - Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: f5773acd-bcb7-4609-89d6-bd2f4255e207)" (RequestToken: ee336312-5f23-9b4e-e1ef-d2373be1afae, HandlerErrorCode: InvalidRequest)`

version: `"serverless-plugin-warmup": "^4.9.0",`

is any old version can support?

**Comment by casperkloppenburg** [comment]
I ran into this issue too. AWS Lambda doesn't support Node.js 12 anymore. Upgrading serverless-plugin-warmup to version 8 did the trick.

**Comment by juanjoDiaz** [comment]
Indeed.

serverless-plugin-warmup uses it's own node version. You should upgrade to a newer plugin version that uses a newer node version.
