### ISSUE TITLE
Description error?

### ISSUE THREAD

**Issue by nbcchen** [juanjoDiaz/serverless-plugin-warmup#350]
In the [Configuration section](https://github.com/juanjoDiaz/serverless-plugin-warmup/blob/main/README.md#configuration) of the README, I see this sentence:

> role Role to apply to the warmer lambda (defaults to the role in the provider)

In reality it creates a role that allows `lambda:InvokeFunction` on the other functions on the stack. Is it an error on the description?

**Comment by juanjoDiaz** [comment]
Hi @nbcchen ,

Can you give me an example YAML or a project to replicate the issue?

The `role` setting should simply apply this role to the function.
If no `role` is provided, then the default role should be created.

**Comment by nbcchen** [comment]
@juanjoDiaz 
in the README it describe the `role` node as below 
Role to apply to the warmer lambda (**defaults to the role in the provider**)

But it does not default to the role in the provider, it instead generates a new role called `WarmUpPluginDefaultRole`

**Comment by juanjoDiaz** [comment]
You are right!
This changed in v5 as stated in the documentation.
But it seems that one part of the docs was not fixed.

Fixed now 🙂
