### ISSUE TITLE
TypeError: Cannot set properties of null (setting 'WarmUpPluginDefaultRole')

### ISSUE THREAD

**Issue by wolff453** [juanjoDiaz/serverless-plugin-warmup#352]
Hi!

I was using the plugin to warm up my functions but I came across a bug. If I don't pass the "role" object in the yml, the plugin gives me an error. However, when I looked at the code, I saw that if there is no role being passed, it creates a default one. The validation that is being done to validate whether the resources object exists is not working, because null is also an object and it can't create the default role because it's not falling for this validation.

In this image, you can see that i'm not passing the role object
![image](https://github.com/juanjoDiaz/serverless-plugin-warmup/assets/77250912/882a74c1-61c1-43b4-9e99-74b889eebdd6)

Error:
![image](https://github.com/juanjoDiaz/serverless-plugin-warmup/assets/77250912/a2edfe20-66f1-449b-a06b-a9dd6d24f9af)

Error location:

![image](https://github.com/juanjoDiaz/serverless-plugin-warmup/assets/77250912/37fc7d20-a998-44f0-bf58-aaed0a12c1f3)

Possible correction:
 Change this validation and check if is a falsy value instead check the type.

**Comment by juanjoDiaz** [comment]
Interesting...
Can you elaborate on which version of the framework, which version of this plugin and which other plugins are you using?

I wonder what is setting the `Resources` object to `null` instead of the default `undefined`.

**Comment by juanjoDiaz** [comment]
Closing due  to no response

**Comment by rewhsu** [comment]
Note: I ran into this too. For some reason, someone on my team had this in a serverless file, without anything defined under `resources`:

```
resources:
```
I removed the line and everything worked fine.
