### ISSUE TITLE
Transform failed with 1 error. ERROR: The symbol "i" has already been declared

### ISSUE THREAD

**Issue by alihasnain-techverx** [juanjoDiaz/serverless-plugin-warmup#355]
I'm trying to upgrade my serverless from node 14 to node 20. These are my package.json changes:
![image](https://github.com/user-attachments/assets/183d2c58-bbdd-47fb-a0f3-9dbbbf099194)

node modules are installed with no error. whenever I run npm run build it throws error every time.
![image](https://github.com/user-attachments/assets/ebe8925c-a282-469d-9987-7a0f16815720)
I commented the plugins used in my serverless and uncommented one by one. Turns out the error is coming from **serverless-plugin-warmup**. When i commented put this plugin the build was successful.
![image](https://github.com/user-attachments/assets/e972e448-1fcf-411b-a18f-18475c748e9e)

I did try to install/update different versions but still getting the issue. Does any body else getting the same issue or is it the issue with the plugin itself.

node : v20.15.1
npm : 10.7.0
serverless:
Framework Core: 3.38.0 (local)
Plugin: 7.2.3
SDK: 4.5.1

**Comment by juanjoDiaz** [comment]
The issue seems to be an incompatibility between the bundle plugin and the warmup plugin.

The bundle plugin shouldn't be bundling the warmer function but for some reason it seems to be doing so.
This is typically caused because different plugins use different lifecycle hooks differently.
I tried the serverless maintainers to provide guidance regarding this to no avail....

I assume that the solution is to configure the bundle plugin to ignore the warmer function

**Comment by alihasnain-techverx** [comment]
> The issue seems to be an incompatibility between the bundle plugin and the warmup plugin.
> 
> The bundle plugin shouldn't be bundling the warmer function but for some reason it seems to be doing so. This is typically caused because different plugins use different lifecycle hooks differently. I tried the serverless maintainers to provide guidance regarding this to no avail....
> 
> I assume that the solution is to configure the bundle plugin to ignore the warmer function

is there any docs/instruction on how I can do it. would appreciate if there is any article/material.

**Comment by juanjoDiaz** [comment]
That's not related to this plugin. It's related to the bundle plugin.
So I recommend that you ask in their repo 🙂

**Comment by alihasnain-techverx** [comment]
used serverless-esbuild instead of serverless-bundle. I believe the issue is with the serverless bundle. you can mark this issue as resolved.

**Comment by rostislav-simonik** [comment]
https://github.com/webpack/webpack/issues/18932
