### ISSUE TITLE
Warm all lambda instead of selected one

### ISSUE THREAD

**Issue by uzair004** [juanjoDiaz/serverless-plugin-warmup#356]
It trigger all lambdas in project even though I am trying to keep a single lambda warm.

**Comment by juanjoDiaz** [comment]
Hi @uzair004 ,

You probably misconfigured something.
I need to yo share your serverles.yaml at least so I can help you.

**Comment by uzair004** [comment]
Closing this issue, as I don't have more details to share. I did manual lambda trigger via cron.
Thanks.
